name: salah_times
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+2

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  path_provider: ^2.1.6
  path: ^1.9.1
  geolocator: ^14.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/cities.json
  fonts:
    # - family: NotoSansArabic
    #   fonts:
    #     - asset: assets/fonts/noto-sans-arabic/NotoSansArabic-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/noto-sans-arabic/NotoSansArabic-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/noto-sans-arabic/NotoSansArabic-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/noto-sans-arabic/NotoSansArabic-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/noto-sans-arabic/NotoSansArabic-Bold.ttf
    #       weight: 700

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Bold.ttf
          weight: 700
